// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh1mDavfR5oQoMqwkFh_8K_NUaEE0Ut0Q',
    appId: '1:851402083225:web:ec11a0e066776216f1a108',
    messagingSenderId: '851402083225',
    projectId: 'newsflow-47cbd',
    authDomain: 'newsflow-47cbd.firebaseapp.com',
    storageBucket: 'newsflow-47cbd.firebasestorage.app',
    measurementId: 'G-0LDL5S9P9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN_RgFycHNOKYvR5Zb3d2QCVoyKqVyOhA',
    appId: '1:851402083225:android:724a5b1a70c2929bf1a108',
    messagingSenderId: '851402083225',
    projectId: 'newsflow-47cbd',
    storageBucket: 'newsflow-47cbd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo_AMDEUeft_47cDJlhUaFvdT6DjoOKxU',
    appId: '1:851402083225:ios:6d56ba9f00c2d071f1a108',
    messagingSenderId: '851402083225',
    projectId: 'newsflow-47cbd',
    storageBucket: 'newsflow-47cbd.firebasestorage.app',
    iosBundleId: 'com.example.newsflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo_AMDEUeft_47cDJlhUaFvdT6DjoOKxU',
    appId: '1:851402083225:ios:6d56ba9f00c2d071f1a108',
    messagingSenderId: '851402083225',
    projectId: 'newsflow-47cbd',
    storageBucket: 'newsflow-47cbd.firebasestorage.app',
    iosBundleId: 'com.example.newsflow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh1mDavfR5oQoMqwkFh_8K_NUaEE0Ut0Q',
    appId: '1:851402083225:web:4418908b0601a949f1a108',
    messagingSenderId: '851402083225',
    projectId: 'newsflow-47cbd',
    authDomain: 'newsflow-47cbd.firebaseapp.com',
    storageBucket: 'newsflow-47cbd.firebasestorage.app',
    measurementId: 'G-VEQRZ63LPX',
  );
}
